### ISSUE TITLE
Add Missing Icon - Home Assistant

### ISSUE THREAD

**Issue by jonathanathe** [mackenly/simple-icons-stream-deck#2]
Good morning,

Thank you for your great work to add this great project within Stream Deck I am new to this (I received it today) I wanted to add the Home Assistant icon that does appear on the web but within Stream Deck this icon does not appear. Would it be possible to update to add this one.

![image](https://user-images.githubusercontent.com/34164094/196028621-7781067c-d759-414d-b158-50cddf9ea406.png)

Thank you!

**Comment by mackenly** [comment]
@jonathanathe This bug is being fixed in #3. There's an issue in #1 that deals with some icons not looking right. Unfortunately, while Home Assistant is now showing up properly, it looks deformed because of that bug.

**Comment by jonathanathe** [comment]
> @jonathanathe This bug is being fixed in #3. There's an issue in #1 that deals with some icons not looking right. Unfortunately, while Home Assistant is now showing up properly, it looks deformed because of that bug.

Thanks!
