### ISSUE TITLE
Icon Pack Won't Download

### ISSUE THREAD

**Issue by sdb67** [mackenly/simple-icons-stream-deck#9]
When the 'Get' button is clicked, a message appears that says I must download the latest version of Elgato, even though I have the latest version. However, it also appears to be trying to produce a download button, but it just spins and then says to open it in Marketplace even though I am in the Elgato marketplace.

**Comment by sdb67** [comment]
Yes, I can but no worries I'll figure it out.

**Comment by mackenly** [comment]
@sdb67 Good to know. I'll try to see if I can replicate.

**Comment by mackenly** [comment]
@sdb67 Pushed out a new update to the pack today. May have changed the download issue.

**Comment by sdb67** [comment]
Terrific thanks, but I was able to fix the issue and download the pack.

Thank you for your assistance.

Sylvia
